import { test, expect, type Page } from "@playwright/test";
import path from "node:path";
import { randomUUID } from "node:crypto";
import { createTargetPost } from "./_target";

// BL-SOCIAL-03a — the FEED MEDIA path (BL-SOCIAL-02 tests 21–24), the class of bug
// unit tests cannot see: D-042 r1–r4 were all browser-only video failures (duration
// Infinity, detached-element seek, poster dims read too early, seek stall), every one
// shipped with CI green. These drive the REAL composer + PostMedia against live prod
// as the hub-seeded verified account A. AUTHENTICATED — skip without E2E_EMAIL.
//
// Fixtures are ffmpeg-generated by scripts/gen-e2e-fixtures.mjs at globalSetup (never
// committed): img1/img2.jpg, short.mp4 (3s H.264/AAC faststart), big.mp4 (95s → trips
// the 90s composer gate). Selectors are the SHIPPED ones (composer.tsx / PostMedia.tsx),
// not the spec-authored ones — verified against the components.

const EMAIL = process.env.E2E_EMAIL;
const PASSWORD = process.env.E2E_PASSWORD;
const GEN = path.join(__dirname, "fixtures", "generated");
const FX = {
  img1: path.join(GEN, "img1.jpg"),
  img2: path.join(GEN, "img2.jpg"),
  short: path.join(GEN, "short.mp4"),
  big: path.join(GEN, "big.mp4"),
};

// Composer selectors (shipped strings, default en locale — baseURL is localhost/en).
const textarea = (page: Page) => page.getByPlaceholder(/share an opportunity/i);
const fileInput = (page: Page) => page.locator('input[type="file"]'); // only one on the feed
const addMediaBtn = (page: Page) => page.getByRole("button", { name: "Photo / video" });
const postBtn = (page: Page) => page.getByRole("button", { name: "Post", exact: true });

// The composer surfaces errors in a <p role="alert"> (Next.js also renders an
// always-present, EMPTY <div role="alert" id="__next-route-announcer__">, so a bare
// getByRole("alert") is ambiguous — scope to the <p>).
const composerError = (page: Page) => page.locator('p[role="alert"]');

// The verified composer's root (data-testid="composer"). SCOPE the "Remove" (staged-media
// delete) count to it: the home page renders the Feed below the composer, and a bookmarked
// post's "Remove from bookmarks" button is a SUBSTRING match on an unscoped name:"Remove"
// locator. post_bookmarks is keyed by user_id, so a bookmark set by the (chromium-only)
// social suite is visible to EVERY project's feed as account A — a cross-project race that
// inflated the count to 3 on chromium-360. Scoping makes the count composer-only.
const composer = (page: Page) => page.getByTestId("composer");

// Stage the given file(s) on the composer's hidden input (fires onChange → onPick),
// then wait for the upload to FINISH and the media to be staged. The reliable signal
// is the staged thumbnails: the composer renders one "Remove" control per item only
// AFTER setMedia runs (which is after the upload). Waiting on the "Photo / video"
// button's enabled state is NOT reliable — it can read as enabled in the gap before
// onPick flips `busy`, letting a post publish with empty media.
async function stageAndWait(page: Page, files: string | string[], expected: number) {
  await fileInput(page).setInputFiles(files);
  await expect(composer(page).getByRole("button", { name: "Remove" })).toHaveCount(expected, { timeout: 30_000 });
  await expect(composerError(page)).toHaveCount(0);
}

// Reuse the ONE session from the "setup" project (auth.setup.ts) instead of login() in
// every beforeEach — this suite is 4 tests x 2 projects = 8 concurrent sign-ins as A
// without it. File-scoped so smoke + attachments keep their own login/logout contexts.
// Path is a literal (NOT imported): Playwright forbids a test file importing another
// test file, and auth.setup.ts is one — it must match `authFile` there.
test.use({ storageState: "e2e/.auth/user.json" });

test.describe("feed media path (authenticated)", () => {
  test.skip(!EMAIL || !PASSWORD, "set E2E_EMAIL / E2E_PASSWORD (verified account A) to run");

  test.beforeEach(async ({ page }) => {
    // login() REMOVED — the file-scoped storageState (auth.setup.ts) already carries an
    // authenticated session; just navigate.
    await page.goto("/", { waitUntil: "domcontentloaded" });
    // A is verified + onboarded, so the composer (not the verify-to-post prompt)
    // renders. Its textarea is the anchor the compose tests drive.
    await expect(textarea(page)).toBeVisible({ timeout: 15_000 });
  });

  // 21 — compose with two images → the new post renders both.
  test("compose with two images renders both in the new post", async ({ page }) => {
    const token = `e2e-2img-${randomUUID()}`;
    await textarea(page).fill(token);
    await stageAndWait(page, [FX.img1, FX.img2], 2);
    await postBtn(page).click();

    const card = page.locator("article", { hasText: token });
    await expect(card).toBeVisible({ timeout: 15_000 });
    const group = card.getByRole("group", { name: /2 images/i });
    await expect(group).toBeVisible();
    await expect(group.locator("img")).toHaveCount(2); // both signed URLs resolved + rendered
  });

  // 22 — compose a video → poster + play button, NO autoplay (<video> only after tap).
  test("compose a video shows a poster + play button, no autoplay, plays on tap", async ({ page }) => {
    const token = `e2e-vid-${randomUUID()}`;
    await textarea(page).fill(token);
    await stageAndWait(page, FX.short, 1); // client reads 3s duration + extracts a poster frame
    await postBtn(page).click();

    const card = page.locator("article", { hasText: token });
    await expect(card).toBeVisible({ timeout: 15_000 });
    const play = card.getByRole("button", { name: "Play video" });
    await expect(play).toBeVisible();
    await expect(card.locator("video")).toHaveCount(0); // nothing autoplays before the tap
    await play.click();
    await expect(card.locator("video")).toHaveCount(1); // <video controls> mounts on tap
  });

  // 23 — a >90s video is rejected in the composer, before any upload.
  test("a >90s video is rejected in the composer and never uploaded", async ({ page }) => {
    await textarea(page).fill(`e2e-big-${randomUUID()}`);
    await fileInput(page).setInputFiles(FX.big);
    // Duration is read from the container bytes (D-042) → too_long → alert, no upload.
    const alert = composerError(page);
    await expect(alert).toBeVisible({ timeout: 30_000 });
    await expect(alert).toContainText(/90 seconds/i);
    // Nothing was staged (rejected before upload) → no "Remove" control appears.
    await expect(composer(page).getByRole("button", { name: "Remove" })).toHaveCount(0);
  });

  // 24 — the post action bar stays a single row (the 5 icons never wrap). Uses a per-run
  // self-provisioned target (Option C — no permanent fixture), hard-deleted by teardown.
  // Assert the LEFTMOST action (Like) and the RIGHTMOST (Bookmark) share a row: a wrapped
  // bookmark would drop ~44px below. (Independent of any summary row.)
  test("the post action bar stays a single row", async ({ page }) => {
    const targetId = await createTargetPost("layout target");
    await page.goto(`/posts/${targetId}`, { waitUntil: "domcontentloaded" });
    const card = page.locator("article").first();
    await expect(card).toBeVisible({ timeout: 15_000 });
    const like = card.getByRole("button", { name: "Like" });
    const bookmark = card.getByRole("button", { name: /save to bookmarks|remove from bookmarks/i });
    await expect(like).toBeVisible();
    await expect(bookmark).toBeVisible();
    const lb = await like.boundingBox();
    const bb = await bookmark.boundingBox();
    expect(lb).not.toBeNull();
    expect(bb).not.toBeNull();
    // Same row → their top edges align within a few px; a second-row wrap is ~44px off.
    expect(Math.abs(lb!.y - bb!.y)).toBeLessThan(12);
  });
});
